# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish windows and linux executables

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish linux
      run: dotnet publish --os linux
    - name: Publish windows
      run: dotnet publish --os win
    - name: Zip linux file
      uses: montudor/action-zip@v1
      with:
        args: zip -j work-linux-${{ github.event.release.tag_name }}.zip bin/Release/net9.0/linux-x64/publish/work
    - name: Zip win file
      uses: montudor/action-zip@v1
      with:
        args: zip -j work-win-${{ github.event.release.tag_name }}.zip bin/Release/net9.0/win-x64/publish/work.exe
    - name: Upload linux release to new github release
      uses: JasonEtco/upload-to-release@master
      with:
        args: work-linux-${{ github.event.release.tag_name }}.zip application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload windows release to new github release
      uses: JasonEtco/upload-to-release@master
      with:
        args: work-win-${{ github.event.release.tag_name }}.zip application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  

  
